In [1]:
import pandas as pd

res = pd.read_csv("results.csv", index_col=0)
res['ARI'] = res['ARI'].apply(lambda x: round(x, 2))
res['NMI'] = res['NMI'].apply(lambda x: round(x, 2))

B_minus = res[res['name'].apply(lambda x: x[:2] == 'B-')]
B_plus = res[res['name'].apply(lambda x: x[:2] == 'B+')]

In [10]:
B_plus_max = B_plus[['name', 'dataset', 'ARI', 'NMI']].groupby(by=['name', 'dataset']).max().reset_index()
B_plus_max['ARI | NMI'] = B_plus_max['ARI'].apply(lambda x: "{:1.2f}".format(x)) + ' | ' + B_plus_max['NMI'].apply(lambda x: "{:1.2f}".format(x))
B_plus_max.pivot(index='name', columns='dataset', values='ARI | NMI')#.to_csv("B_plus.csv")

dataset,BSP_GAP_3,BSP_GAP_4,BSP_GAP_5,Fungi_genera_3,Fungi_genera_4,Fungi_genera_5,Fungi_genera_6,Fungi_genera_7
name,,,,,,,,
B+ A0 IKM,0.78 | 0.78,0.69 | 0.79,0.50 | 0.57,0.62 | 0.56,0.59 | 0.64,0.47 | 0.58,0.38 | 0.53,0.32 | 0.48
B+ A0 KM,0.73 | 0.75,0.65 | 0.78,0.50 | 0.57,0.77 | 0.70,0.64 | 0.69,0.50 | 0.61,0.36 | 0.51,0.34 | 0.51
B+ A1 IKM,0.85 | 0.87,0.66 | 0.70,0.50 | 0.62,0.81 | 0.76,0.58 | 0.63,0.55 | 0.65,0.41 | 0.56,0.38 | 0.56
B+ A1 IKM 3d,0.92 | 0.92,0.65 | 0.70,0.48 | 0.60,0.52 | 0.56,0.42 | 0.48,0.33 | 0.48,0.37 | 0.53,0.33 | 0.52
B+ A1 IKM A2,0.85 | 0.87,0.65 | 0.74,0.68 | 0.77,0.81 | 0.76,0.78 | 0.77,0.55 | 0.64,0.46 | 0.59,0.43 | 0.57
B+ A1 IKM A2 3d,0.92 | 0.92,0.63 | 0.68,0.61 | 0.70,0.71 | 0.67,0.36 | 0.47,0.42 | 0.54,0.41 | 0.55,0.29 | 0.50
B+ A1 KM,0.79 | 0.83,0.65 | 0.75,0.49 | 0.61,0.81 | 0.76,0.58 | 0.63,0.55 | 0.65,0.42 | 0.56,0.38 | 0.52
B+ A1 KM 3d,0.92 | 0.92,0.62 | 0.69,0.42 | 0.57,0.55 | 0.56,0.42 | 0.51,0.38 | 0.50,0.34 | 0.52,0.33 | 0.51
B+ A1 KM A2,0.85 | 0.87,0.69 | 0.79,0.61 | 0.71,0.77 | 0.70,0.78 | 0.77,0.58 | 0.68,0.46 | 0.58,0.41 | 0.56
B+ A1 KM A2 3d,0.85 | 0.87,0.61 | 0.68,0.56 | 0.66,0.48 | 0.54,0.44 | 0.51,0.49 | 0.61,0.42 | 0.56,0.33 | 0.52
B+ A2 IKM,0.25 | 0.35,0.72 | 0.78,0.55 | 0.66,0.55 | 0.50,0.44 | 0.52,0.38 | 0.50,0.33 | 0.48,0.37 | 0.53
B+ A2 IKM 3d,0.17 | 0.30,0.68 | 0.74,0.47 | 0.56,0.55 | 0.50,0.44 | 0.52,0.31 | 0.45,0.32 | 0.48,0.35 | 0.53
B+ A2 KM,0.85 | 0.87,0.70 | 0.75,0.51 | 0.65,0.55 | 0.50,0.58 | 0.60,0.38 | 0.50,0.42 | 0.56,0.37 | 0.53
B+ A2 KM 3d,0.85 | 0.87,0.65 | 0.70,0.45 | 0.60,0.55 | 0.50,0.47 | 0.53,0.38 | 0.50,0.37 | 0.52,0.34 | 0.50

In [12]:
B_minus_20 = B_minus[B_minus['iter'].isin(range(20))]
B_minus_20_max = B_minus_20[['name', 'dataset', 'ARI', 'NMI']].groupby(by=['name', 'dataset']).max().reset_index()
B_minus_20_max['ARI | NMI'] = B_minus_20_max['ARI'].apply(lambda x: "{:1.2f}".format(x)) + ' | ' + B_minus_20_max['NMI'].apply(lambda x: "{:1.2f}".format(x))
B_minus_20_max.pivot(index='name', columns='dataset', values='ARI | NMI')#.to_csv("B_minus_20.csv")

dataset,BSP_GAP_3,BSP_GAP_4,BSP_GAP_5,Fungi_genera_3,Fungi_genera_4,Fungi_genera_5,Fungi_genera_6,Fungi_genera_7
name,,,,,,,,
B- A0 IKM,0.92 | 0.92,0.69 | 0.80,0.58 | 0.74,0.50 | 0.50,0.61 | 0.66,0.54 | 0.65,0.40 | 0.56,0.37 | 0.53
B- A0 KM,0.92 | 0.92,0.68 | 0.79,0.61 | 0.72,0.81 | 0.76,0.64 | 0.69,0.54 | 0.63,0.43 | 0.56,0.41 | 0.57
B- A1 IKM,0.92 | 0.92,0.71 | 0.77,0.57 | 0.67,0.81 | 0.76,0.78 | 0.78,0.59 | 0.66,0.54 | 0.66,0.51 | 0.63
B- A1 IKM 3d,1.00 | 1.00,0.72 | 0.82,0.56 | 0.67,0.86 | 0.82,0.79 | 0.78,0.56 | 0.66,0.52 | 0.64,0.49 | 0.61
B- A1 KM,1.00 | 1.00,0.69 | 0.81,0.57 | 0.69,0.85 | 0.82,0.78 | 0.78,0.56 | 0.67,0.55 | 0.66,0.49 | 0.61
B- A1 KM 3d,1.00 | 1.00,0.70 | 0.79,0.63 | 0.73,0.86 | 0.82,0.78 | 0.77,0.58 | 0.67,0.54 | 0.65,0.49 | 0.61
B- A2 IKM,1.00 | 1.00,0.73 | 0.85,0.51 | 0.64,0.81 | 0.76,0.69 | 0.72,0.54 | 0.64,0.44 | 0.57,0.39 | 0.54
B- A2 IKM 3d,0.92 | 0.92,0.72 | 0.84,0.55 | 0.67,0.76 | 0.72,0.72 | 0.76,0.49 | 0.61,0.47 | 0.59,0.42 | 0.57
B- A2 KM,0.92 | 0.92,0.69 | 0.79,0.52 | 0.63,0.81 | 0.76,0.78 | 0.77,0.52 | 0.63,0.52 | 0.63,0.48 | 0.60
B- A2 KM 3d,0.92 | 0.92,0.64 | 0.73,0.56 | 0.70,0.81 | 0.78,0.67 | 0.70,0.57 | 0.65,0.47 | 0.60,0.44 | 0.59

In [14]:
B_minus_max = B_minus[['name', 'dataset', 'ARI', 'NMI']].groupby(by=['name', 'dataset']).max().reset_index()
B_minus_max['ARI | NMI'] = B_minus_max['ARI'].apply(lambda x: "{:1.2f}".format(x)) + ' | ' + B_minus_max['NMI'].apply(lambda x: "{:1.2f}".format(x))
B_minus_max.pivot(index='name', columns='dataset', values='ARI | NMI')#.to_csv("B_minus_100.csv")

dataset,BSP_GAP_3,BSP_GAP_4,BSP_GAP_5,Fungi_genera_3,Fungi_genera_4,Fungi_genera_5,Fungi_genera_6,Fungi_genera_7
name,,,,,,,,
B- A0 IKM,0.92 | 0.92,0.72 | 0.84,0.60 | 0.74,0.77 | 0.70,0.61 | 0.66,0.54 | 0.65,0.45 | 0.60,0.41 | 0.55
B- A0 KM,0.92 | 0.92,0.68 | 0.79,0.61 | 0.72,0.81 | 0.76,0.64 | 0.69,0.56 | 0.66,0.47 | 0.61,0.45 | 0.57
B- A1 IKM,1.00 | 1.00,0.72 | 0.84,0.61 | 0.70,0.81 | 0.76,0.78 | 0.78,0.59 | 0.67,0.57 | 0.68,0.51 | 0.63
B- A1 IKM 3d,1.00 | 1.00,0.73 | 0.82,0.64 | 0.74,0.86 | 0.84,0.79 | 0.78,0.59 | 0.69,0.55 | 0.67,0.51 | 0.64
B- A1 KM,1.00 | 1.00,0.72 | 0.81,0.65 | 0.74,0.85 | 0.82,0.78 | 0.78,0.59 | 0.68,0.57 | 0.68,0.50 | 0.62
B- A1 KM 3d,1.00 | 1.00,0.72 | 0.82,0.65 | 0.76,0.86 | 0.82,0.78 | 0.78,0.58 | 0.68,0.54 | 0.65,0.51 | 0.64
B- A2 IKM,1.00 | 1.00,0.73 | 0.85,0.57 | 0.72,0.81 | 0.76,0.78 | 0.77,0.55 | 0.65,0.52 | 0.63,0.47 | 0.61
B- A2 IKM 3d,0.92 | 0.92,0.72 | 0.84,0.56 | 0.68,0.81 | 0.78,0.72 | 0.76,0.55 | 0.64,0.47 | 0.60,0.44 | 0.59
B- A2 KM,1.00 | 1.00,0.73 | 0.85,0.61 | 0.71,0.81 | 0.76,0.78 | 0.77,0.59 | 0.67,0.53 | 0.64,0.48 | 0.60
B- A2 KM 3d,0.92 | 0.92,0.72 | 0.84,0.56 | 0.70,0.85 | 0.82,0.75 | 0.74,0.58 | 0.68,0.52 | 0.64,0.47 | 0.60